### ISSUE TITLE
Failed to handle file names

### ISSUE THREAD

**Issue by rimeju** [pidu/git-timemachine#48]
An error is generated when a file or folder(of project) has blank spaces between words, for example: "Sofilab Projects", "Web Dev", etc...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: [git-time-machine](https://github.com/littlebee/git-time-machine) package, v1.2.5

### Stack Trace

Uncaught Error: Command failed: cd /Users/JRivero/Documents/Sofilab Projects/Ruth/library/js && git log --pretty='format:{#/dquotes/id#/dquotes/: #/dquotes/%H#/dquotes/, #/dquotes/authorName#/dquotes/: #/dquotes/%an#/dquotes/, #/dquotes/relativeDate#/dquotes/: #/dquotes/%cr#/dquotes/, #/dquotes/authorDate#/dquotes/: %at,  #/dquotes/message#/dquotes/: #/dquotes/%s#/dquotes/, #/dquotes/body#/dquotes/: #/dquotes/%b#/dquotes/, #/dquotes/hash#/dquotes/: #/dquotes/%h#/dquotes/}' --topo-order --date=local --numstat /Users/JRivero/Documents/Sofilab Projects/Ruth/library/js/security.js
/bin/sh: line 0: cd: /Users/JRivero/Documents/Sofilab: No such file or directory

```
At child_process.js:496

Error: Command failed: cd /Users/JRivero/Documents/Sofilab Projects/Ruth/library/js && git log --pretty='format:{#/dquotes/id#/dquotes/: #/dquotes/%H#/dquotes/, #/dquotes/authorName#/dquotes/: #/dquotes/%an#/dquotes/, #/dquotes/relativeDate#/dquotes/: #/dquotes/%cr#/dquotes/, #/dquotes/authorDate#/dquotes/: %at,  #/dquotes/message#/dquotes/: #/dquotes/%s#/dquotes/, #/dquotes/body#/dquotes/: #/dquotes/%b#/dquotes/, #/dquotes/hash#/dquotes/: #/dquotes/%h#/dquotes/}' --topo-order --date=local --numstat /Users/JRivero/Documents/Sofilab Projects/Ruth/library/js/security.js
/bin/sh: line 0: cd: /Users/JRivero/Documents/Sofilab: No such file or directory

    at checkExecSyncError (child_process.js:453:13)
    at Object.execSync (child_process.js:493:13)
    at Function.module.exports.GitLogUtils._fetchFileHistory (/Users/JRivero/.atom/packages/git-time-machine/node_modules/git-log-utils/lib/git-log-utils.js:58:27)
    at Function.module.exports.GitLogUtils.getCommitHistory (/Users/JRivero/.atom/packages/git-time-machine/node_modules/git-log-utils/lib/git-log-utils.js:39:21)
    at GitTimeMachineView.module.exports.GitTimeMachineView._renderTimeline (/Users/JRivero/.atom/packages/git-time-machine/lib/git-time-machine-view.coffee:65:22)
    at GitTimeMachineView.module.exports.GitTimeMachineView.render (/Users/JRivero/.atom/packages/git-time-machine/lib/git-time-machine-view.coffee:32:8)
    at GitTimeMachineView.module.exports.GitTimeMachineView.setEditor (/Users/JRivero/.atom/packages/git-time-machine/lib/git-time-machine-view.coffee:24:6)
    at Object.module.exports.GitTimeMachine.toggle (/Users/JRivero/.atom/packages/git-time-machine/lib/git-time-machine.coffee:39:27)
    at atom-workspace.subscriptions.add.atom.commands.add.git-time-machine:toggle (/Users/JRivero/.atom/packages/git-time-machine/lib/git-time-machine.coffee:17:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:45 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:19.4.0 git-time-machine:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.20
git-time-machine, v1.2.5

# Dev
No dev packages
```

**Comment by syohex** [comment]
This repository is a Emacs package.
I think you should report your issue to https://github.com/littlebee/git-time-machine Atom package.

**Comment by pidu** [comment]
:-)
